### ISSUE TITLE
ORF-downloads funktionieren nicht (mehr)

### ISSUE THREAD

**Issue by GerhardTatschl** [mediathekview/mediathekviewweb#170]
Hello,

When I installed the versin 13.5.1., there was a hint how to configure mediathekview so that ORF-downloads should work.
That was o.k., but only some weeks later the ORF-Downloads didn't work anymore and when I try to download ORF-films i get only "fehlerhaft"

What's wrong ?

**Comment by DaDirnbocher** [comment]
You are talking about version 13.5.1, which means you are talking about the program MediathekView, not the webapplication mediathekviewweb, So you should ask this question in https://github.com/mediathekview/MediathekView or better in https://forum.mediathekview.de/category/4/fragen-hilfe-kritik.

[The short answer](https://forum.mediathekview.de/topic/3484/download-von-orf-in-%C3%B6sterreich-weiterhin-nicht-m%C3%B6glich?_=1594751597818) for your question is (probably) use "Moozilla", "mozilla" or something else as user agent instead of "Mozilla". It seems ORF has blocked "Mozilla" for Windowsusers.
