### ISSUE TITLE
legality of this appliation / Legalität ?

### ISSUE THREAD

**Issue by 18iteration** [mediathekview/mediathekviewweb#188]
How legal is this program in case of downloading zdfneo or ARD medias from your site? Is this piracy?

I am aware of perhaps uninteded iligal content but I am strictly speaking of offical providers like the ones listed above on your site.

**Comment by bagbag** [comment]
Some non-legal justification: MediathekViewWeb exists for some years now. MediathekView even way longer (around 10 years I think). We never received any complaints from ARD/ZDF/etc. They once even mentioned MVW in one of their shows. I regularly get invited to some events from ZDF (which I never attend).

And some legal stuff: We do not provide/serve the content ourself but instead just link to their servers. All research I did about the legality of this came to the conclusion, that it is totally legal. We even "won" a litigation, because they realized, that what we do is legal: [https://mediathekview.de/news/abmahnung_mediathekview/](https://mediathekview.de/news/abmahnung_mediathekview/).

I am no expert in that topic at all, so all of this is without guarantee.

**Comment by marcusfey** [comment]
The content is not provided by this project but by the respective TV stations. This project only provides direct links to content that already exists.
