### ISSUE TITLE
[enhancement] download to server

### ISSUE THREAD

**Issue by TheAlgorythm** [mediathekview/mediathekviewweb#211]
It would be great to be able to configure the service in such a way that it is possible to download the content to a predefined location on the server.
This would help to integrate in a workflow with other services like [Jellyfin](https://jellyfin.org) or Plex.
There should be possible to have a list of predefined locations and the name should be changeable by the user.

**Comment by bagbag** [comment]
I'm not exactly sure what you mean. Click download and the file gets downloaded onto an other client? How should mvw access that?

**Comment by TheAlgorythm** [comment]
My idea is that mvw has a button, when this feature is activated on the self-hosted instance, which starts a process on the server side like `curl --output {download_dir}/{video_name} {video_url}`. This would allow another service to access the same directory as their media directory. The workflow is now to download the videos to the client computer and then upload it onto the server. So the difference is to download it to the server and not to the client. I hope it is now clear.

**Comment by bagbag** [comment]
That's absolutely out of scope. That's not what MVW is made for. Out of interest: why are you hosting it yourself?

What may will come with MvW 2.0 are user accounts and a client you can run somewhere which will automatically download stuff you mark on the webclient.

**Comment by TheAlgorythm** [comment]
> That's absolutely out of scope.

I was afraid of it. But it was worth a try.

> Why are you hosting it yourself?

Well, i don't, but I would have with this feature. As it would streamline the process of downloading videos to the main media service Jellyfin. As long as the new client won't run headless/web-based as a service this won't help.
Imho a new app would further fragmentise media consumption. Therefore a lot of users with a media server would like such a feature, as it resembles partly the Unix philosophy "Make each program do one thing well". But I understand that it is out of scope.
For all interested in such a feature there is [youtube-dl-server](https://github.com/manbearwiz/youtube-dl-server) which is built for this use-case but lacks nearly all the other features of MvW like search.

**Comment by d0x7** [comment]
I just found this issue, because I was looking for the same thing. +1 for adding this. Currently I go to MvW, search then copy the link, paste it into JD & download it,  so I can watch it from Emby/Jellyfin. A button like the current video button, which would add the movie, in a previously selected quality, to the download queue, would be very, very useful. I think much more than just the two of us would make use of this. 

As the original MediathekView is written in java; is this just a frontend using the java library, or has MvW a duplicate codebase, doing the same thing, but in Typescript (plus website obviously)? Thinking about using the java client as a library, without GUI and coding a similar website, with a search and a download functionality. I'm just not sure whether querying ARD/ZDF/etc. is a lot of work = using the existing client would save me a lot of work, of if it's just a matter of one or two API requests and then processing the data, so I could just do it much easier by myself. I'll maybe look into that.

> That's absolutely out of scope.

That's unfortunate, but still +1. Maybe one day.. :)

**Comment by TheAlgorythm** [comment]
>Thinking about using the java client as a library, without GUI and coding a similar website, with a search and a download functionality.

Forking this should be easier, as it would involve only a bit of fronted and a download component should be pretty easy to code.

Btw. what is JD?

**Comment by frostworx** [comment]
I was just looking for that function as well.

Would have been nice to be able to browse the content (_while traveling or while using a mobile device in lan)_, but download to your server _(so possibly directly to your kodi media)_ instead of the client device. Could have been also a nice integration for home assistant for example.

Thanks for opening up the feature request

_(JD likely is jdownloader in above context)_
